In [21]:
from google.colab import drive
drive.mount('/content/drive')
import tensorflow as tf
import keras
import matplotlib.pyplot as plt
import re
import numpy as np
import os
import pandas
from sklearn.cluster import KMeans

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
"""
this function divides the length of whatever 
size the list is by 4 for a 4mer
"""
def BaseFunction(x,y): 
    return((len(x)//y),y)

In [0]:
"""
this function provides information about the array    
"""
def array_inspect(x):
    print ("shape=",(x.shape),"len=",len(x),"ndim=",x.ndim,"size=",x.size,"dtype=",x.dtype)

In [0]:
"""
this function normalizes the raw signal resistances
from each read by dividing by the mean(or std?)
"""
def normalize(x,y):
    z=np.divide(x,y)
    return z

In [0]:
def processing (fasta, *args):
  b = (fasta.split(">", *args))
  print("There are", len(b), "number of reads in this file")
  base = [re.sub(">|\n|\d", "",str) for str in b]
  baseA0 = [re.sub("A","0",str) for str in base]
  baseT1 = [re.sub("T","1",str) for str in baseA0]
  baseG2 = [re.sub("C","2",str) for str in baseT1]
  base_coded = [re.sub("G","3",str) for str in baseG2]
  A0=(a.count("A")) 
  T1=(a.count("T"))
  G2=(a.count("G"))
  C3=(a.count("C"))
  names = ['A', 'C', 'G', 'T']
  values = [(A0), (C3), (G2), (T1)]
  print("A:",values[0])
  print("C:",values[1])
  print("G:",values[2])
  print("T:",values[3])
  #plt.subplot()
  #plt.bar(names, values)
  #plt.suptitle('Nucleotides in all reads')
  #plt.show()

  for x in range(len(base_coded)):
    l=list(int (i) for i in base_coded[x])# this is a comma list of every bp in 0-4
    for y in range(1):
        i=(l.count(y), l.count(y+1), l.count(y+2), l.count(y+3))
        kmercount.append(i)
        n=np.transpose(kmercount) # creates a 2D matrix with the bases counts as rows(ATGC) and the reads by columns
        kmer = n.view() #Create a view of the array with the same data
    d=np.asarray(l)
    #d.resize((BaseFunction(d,kmersize))) #Enter the list and the desired kmer for the function
    v=(str(d))
    reads.append(d) # store the reads in an array called reads
    c=len(d)
    readslength.append(c) #store the amt of kmer reads in readlength=
  #plt.ioff()
  #plt.title("Readlengths")
  #plt.ylabel('number of bases')
  #plt.xlabel('read id')
  #plt.plot(readslength)
  #plt.show() 

In [0]:
kmer=[]
kmercount=[]
reads=[]
readslength=[]


In [27]:
f = open('/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/fasta/test_corrected.fasta',"r") #opens the file with the reads
a = f.read()

print(a[:100])
processing(a)

CAGAACCGCTTTAGCCGCCAGCTGTACTATGCGCTGCACTCCTTTGAGATCGTCATCCCGCCGCTGCGCGCCCGACGCAACAGTATTCCGTCGCTGGTGC
There are 4000 number of reads in this file
A: 6237767
C: 8364979
G: 8372067
T: 6253660


In [0]:
reads = np.load("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/datasets/reads-raw.npy")

In [29]:

print(len(reads))
print(len(reads[0]))
print(len(reads[1]))
print(reads[0][:2])
print(reads[0][:100])
#array_inspect(reads)

4000
5498
4882
[2 0]
[2 0 3 0 0 2 2 3 2 1 1 1 0 3 2 2 3 2 2 0 3 2 1 3 1 0 2 1 0 1 3 2 3 2 1 3 2
 0 2 1 2 2 1 1 1 3 0 3 0 1 2 3 1 2 0 1 2 2 2 3 2 2 3 2 1 3 2 3 2 3 2 2 2 3
 0 2 3 2 0 0 2 0 3 1 0 1 1 2 2 3 1 2 3 2 1 3 3 1 3 2]


In [0]:
np.save("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/datasets/reads-raw.npy", reads)
readslength=np.array(readslength, dtype = int)
np.save("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/datasets/readslength-raw.npy", readslength)

In [0]:
"""
The cell does the following:
    1) Import the signal level data
    2) Normalize it to the mean fof the signal
    3) Appends the signal data from each read into a row of an array given the read count
"""
#1) LOAD THE PREVIOUSLY ARRANGED AND NORMALIZED DATA

sig = np.load("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/datasets/sig_norm_concat.npy")


In [0]:
#2)APPEND THE SIGNAL DATA FROM EACH READ INTO A ROW OF AN ARRAY GIVEN THE READ COUNT

means = [] 
std = []
sig = []
sig2 = []
for x in range(4000):
    a=np.loadtxt("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/signal2/signal/signel_{}.txt".format(x), delimiter='\n') # load the signal
    m=a.mean() #obtain the average signal from the read
    b=normalize(m,a) # divide each resistance by the average to normalize 
    #c=b.size #obtains the number of resistance signals per read
    #print("resist",c)
    #d=readslength[x+1] #obtains the kmers count per read
    #print("kmer",d)
    #e=SigFunction(c,d) #figures out the average amount of resistances per kmer
    #print("Signal",x,"2D array size={}".format(e))
    #sig2.append(a)
    #b.resize(e) # Insert the (#bases,#sig) changes the signal level n signals wide
    sig.append(b)
    #np.save("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/signal2/signalnorm/numpy/sig_norm_{}.npy".format(x), b)
    if x%250==0:
      print("Finished signal_{}.txt".format(x))
np.save("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/datasets/sig_norm_concat_non_ker.npy", sig)

Finished signal_0.txt
Finished signal_250.txt
Finished signal_500.txt


In [0]:
sig=np.load("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/datasets/sig_norm_concat_non_ker.npy")


In [0]:
array_inspect(sig)
array_inspect(sig[0])
array_inspect(reads[0])
print(sig[0][:75])

In [0]:
def remove_insignificant_data(arr, delta, min_len):
  good_arr = []
  temp_arr = []

  for i in range(len(arr)):
    if i == 0:
      temp_arr.append(arr[i])
      continue

    if(abs(arr[i-1] - arr[i]) <= delta):
      temp_arr.append(arr[i])
      continue

    if(len(temp_arr) >= min_len):
      good_arr.append(temp_arr)

    temp_arr = [arr[i]]

  if(len(temp_arr) >= min_len):
    good_arr.append(temp_arr)
  
  return good_arr

In [0]:
ret_arr_sig = np.array(remove_insignificant_data(np.round(sig[0],4), 0.005, 3))
ret_arr_reads = remove_insignificant_data(reads[10], 0.5, 1)
print(len(sig[1]))
print(len(reads[1]))
print(len(ret_arr_sig))
print(len(ret_arr_reads))
print(ret_arr_sig[:10])
print(ret_arr_reads[:10])
print(reads[0][:50])

32793
4882
4671
2912
[list([1.1694, 1.1694, 1.1694, 1.1694, 1.1694, 1.1694, 1.1694, 1.1694])
 list([1.2874, 1.2874, 1.2874, 1.2874, 1.2874])
 list([1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604, 1.0604])
 list([0.8751, 0.8751, 0.8751, 0.8751, 0.8751, 0.8751])
 list([0.9578, 0.9578, 0.9578, 0.9578, 0.9578])
 list([1.0418, 1.0418, 1.0418, 1.0418, 1.0418, 1.0418, 1.0418])
 list([0.9707, 0.9707, 0.9707, 0.9707, 0.9707])
 list([0.9211, 0.9211, 0.9211, 0.9211, 0.9211, 0.9211, 0.9211])
 list([0.8932, 0.8932, 0.8932, 0.8932, 0.8932])
 list([1.0816, 1.0816, 1.0816, 1.0816, 1.0816, 1.0816, 1.0816])]
[[2], [3], [2], [0], [2, 2], [3], [1], [3], [2], [1]]
[2 0 3 0 0 2 2 3 2 1 1 1 0 3 2 2 3 2 2 0 3 2 1 3 1 0 2 1 0 1 3 2 3 2 1 3 2
 0 2 1 2 2 1 1 1 3 0 3 0 1]


In [0]:
flat_arr_sig = []
flat_arr_read = []

for arr in ret_arr_sig:
  flat_arr_sig.extend(arr)
  
for arr in ret_arr_reads:
  flat_arr_read.extend(arr)

flat_arr_sig = np.array(flat_arr_sig)
flat_arr_read = np.array(flat_arr_read)

In [0]:
km = KMeans(4)
km.fit(flat_arr_sig.reshape(-1,1))
print(km.cluster_centers_)

[[1.08347727]
 [0.94865965]
 [0.8572254 ]
 [1.24288209]]


In [0]:
predict_arr = []
for i in flat_arr_sig:
  predict_arr.extend(km.predict(np.array(i).reshape(-1,1)))



In [0]:
print(predict_arr[:100])

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]


In [0]:
prev = -1
condensed_arr = []
for x in predict_arr[:100]:
  if x != prev:
    prev = x
    condensed_arr.append(x)


print(flat_arr_read[:10])
print(np.array(condensed_arr))

[2 3 2 0 2 2 3 1 3 2]
[3 0 2 1 0 1 2 0 2 1 0]


In [0]:
x_train=np.load("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/datasets/x_train_concat.npy")
y_train=np.load("/content/drive/My Drive/Colab Notebooks/tensorflow_basecaller/datasets/y_train_concat.npy")
array_inspect(x_train)
array_inspect(y_train)
shape= (4095422, 46) len= 4095422 ndim= 2 size= 188389412 dtype= float64
shape= (4095422, 7) len= 4095422 ndim= 2 size= 28667954 dtype= float64